name: Construir OrionLauncher

on:
  push:
    branches: [ "main", "master" ]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Generar Keystore temporal
        run: |
          keytool -genkey -v \
            -keystore $RUNNER_TEMP/keystore.jks \
            -alias mykeyalias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass mypassword \
            -keypass mypassword \
            -dname "CN=Orion, OU=Dev, O=Dev, L=City, ST=State, C=US"

      - name: Compilar y firmar APKs con Gradle
        env:
          KEYSTORE_FILE: ${{ runner.temp }}/keystore.jks
          KEYSTORE_PASSWORD: mypassword
          KEY_ALIAS: mykeyalias
          KEY_PASSWORD: mypassword
        run: ./gradlew assembleRelease --no-daemon

      - name: Subir APKs firmadas como artefactos descargables
        uses: actions/upload-artifact@v4
        with:
          name: OrionLauncher-ARM-APKs
          path: |
            app/build/outputs/apk/release/*armeabi-v7a*.apk
            app/build/outputs/apk/release/*arm64-v8a*.apk
