name: Build Orion

on:
  push:
    branches: [ "main", "master" ]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Compilar APKs por Arquitectura (ARM 32 y 64 bit)
        run: ./gradlew assembleRelease --no-daemon

      - name: Firmar APKs
        id: sign_app
        uses: r3d-buck/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Subir APKs firmadas como artefactos descargables
        uses: actions/upload-artifact@v4
        with:
          name: Orion-Launcher-ARM-APKs
          path: |
            app/build/outputs/apk/release/*armeabi-v7a*-signed.apk
            app/build/outputs/apk/release/*arm64-v8a*-signed.apk
          retention-days: 14
